name: 'Create Deployment for Public API'
description: Runs serverless commands.
author: Trace Baxter

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
inputs:
  msg:
    description: msg to show in deployment description
    required: true
  stage:
    description: api stage to deploy to
    required: false
    default: dev
  debug:
    description: verbosity of deploy script
    required: false
    default: 'true'