name: 'Create Deployment for Public API'
description: Runs serverless commands.
author: Trace Baxter
inputs:
  args:
    description: arguments for sls command
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
branding:
  icon: 'arrow-up-right' 
  color: orange